---
# Source: env0-agent/templates/tests/03-toleration-affinity-test.yml
apiVersion: v1
kind: Pod
metadata:
  name: &name "agent-toleration-affinity-test"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  
  
  containers:
    - name: *name
      image: ghcr.io/env0/deployment-agent:dev
      imagePullPolicy: Always
      
      
      command:
        - /bin/bash
        - -ec
        - |
          echo "✅💾 Pod scheduled successfully with provided toleration/affinity setting!"


  
  
  affinity: 
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodegroup
                  operator: In
                  values:
                  - env0-system
