---
# Source: env0-agent/templates/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: env0-secrets-agent
data:
  AGENT_ACCESS_TOKEN: "ZW52MGFnZW50X3Rlc3QtYWdlbnQta2V5X3Rlc3QtYXBpLWd3LWtleQ=="
  ASSUMER_ACCESS_KEY_ID: "YXNzdW1lcktleUlkRW5jb2RlZA=="
  ASSUMER_SECRET_ACCESS_KEY: "YXNzdW1lclNlY3JldEVuY29kZWQ="
  INFRACOST_API_KEY: "aW5mcmFjb3N0"
  CUSTOMER_AWS_ACCESS_KEY_ID: ""
  CUSTOMER_AWS_SECRET_ACCESS_KEY: ""
  CUSTOMER_GOOGLE_PROJECT: ""
  CUSTOMER_GOOGLE_CREDENTIALS: ""
  CUSTOMER_AZURE_CLIENT_ID: ""
  CUSTOMER_AZURE_CLIENT_SECRET: ""
  CUSTOMER_AZURE_TENANT_ID: ""
  BITBUCKET_SERVER_CREDENTIALS: ""
  GITLAB_ENTERPRISE_CREDENTIALS: ""
  GITHUB_ENTERPRISE_APP_PRIVATE_KEY: ""
  ENV0_ENVIRONMENT_OUTPUT_ENCRYPTION_KEY: ""

  

  
  # customerVaultTokenEncoded and customerVaultUrl are deprecated
