# Default values for env0-deployment.
stateMountPath: "/mnt/private/env0"
agentProxy:
  install: true
  replicas: 1
  maxConcurrentRequests: 500
  maxOldSpaceSize: 600
agentTrigger:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    memory: 1000Mi
#requests:
#  cpu: 200m
#  memory: 500Mi
limits:
  cpu: 460m
  memory: 1500Mi
jobHistoryLimitSuccess: 10
jobHistoryLimitFailure: 10
