kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-trigger-role-binding-{{ .Values.agentKey }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: agent-trigger-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: agent-trigger-role-{{ .Values.agentKey }}
  apiGroup: rbac.authorization.k8s.io
