agentThrottling:
  enabled: true
  maxConcurrentJobsPerOrganization: 100
  tasksPollingInterval: 5000
deploymentPodWarmPoolSize: 10
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nodegroup
              operator: In
              values:
                - env0-system
deploymentAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: nodegroup
            operator: In
            values:
              - env0-deployment
