{{- if .Values.agentProxy }}
{{- if .Values.agentProxy.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.agentKey }}.agent-proxy-deployment
  labels:
    env0: agent-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      env0: agent-proxy
  template:
    metadata:
      labels:
        env0: agent-proxy
        {{- if .Values.agentAdditionalLabels }}
          {{- .Values.agentAdditionalLabels | toYaml | nindent 8 -}}
        {{- end }}
      annotations:
        forcePodRestart: {{ randAlphaNum 5 | quote }}
        {{- if .Values.agentAdditionalAnnotations }}
          {{- .Values.agentAdditionalAnnotations | toYaml | nindent 8 -}}
        {{- end }}
    spec:
      volumes:
        {{- include "env0-agent.customCertificatesVolumes" . | nindent 10 }}
      restartPolicy: Always
      {{ if hasKey .Values "agentImagePullSecret" }}
      imagePullSecrets:
        - name: env0-image-pull-secret-{{ .Values.agentKey }}
      {{ end }}
      containers:
        - name: env0-agent-proxy
{{ include "env0-agent.strict-security-context" . | indent 10 }}
          image: {{ .Values.dockerImage }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            # update-ca-certificates must be called before node starts
            - update-ca-certificates;
              node --enable-source-maps run-proxy.js;
          resources:
            limits:
              {{ if .Values.agentProxy.limits }}
              {{ if .Values.agentProxy.limits.cpu }}
              cpu: {{ .Values.agentProxy.limits.cpu }}
              {{end}}
              memory: {{ .Values.agentProxy.limits.memory }}
              {{ else }}
              # backwards defaults
              cpu: 250m
              memory: 500Mi
              {{ end }}
            {{ if .Values.agentProxy.requests }}
            requests:
              cpu: "{{ .Values.agentProxy.requests.cpu }}"
              memory: "{{ .Values.agentProxy.requests.memory }}"
            {{ end }}
          volumeMounts:
            {{- include "env0-agent.customCertificatesVolumesMounts" . | nindent 12 }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: env0-secrets-{{ .Values.agentKey }}
            {{- if .Values.env0ConfigSecretName }}
            - secretRef:
                name: {{ .Values.env0ConfigSecretName }}
            {{- end }}
          env:
            {{- include "env0-agent.http-proxy" . | indent 12 }}
            - name: GITLAB_ENTERPRISE_BASE_URL_SUFFIX
              value: {{ .Values.gitlabEnterpriseBaseUrlSuffix | default "" | quote  }}
            - name: GITHUB_ENTERPRISE_APP_ID
              value: {{ .Values.githubEnterpriseAppId | default "" | quote }}
            - name: GITHUB_ENTERPRISE_APP_CLIENT_ID
              value: {{ .Values.githubEnterpriseAppClientId | default "" | quote }}
            - name: GITHUB_ENTERPRISE_APP_INSTALLATION_ID
              value: {{ .Values.githubEnterpriseAppInstallationId | default "" | quote }}
            - name: STAGE
              value: "{{ .Values.agentKey }}"
            - name: ENV0_STAGE
              value: "{{ .Values.stage }}"
            - name: IS_SELF_HOSTED_K8S
              value: "{{ .Values.isSelfHosted }}"
            - name: OUTPUT_LOGS_LOG_GROUP_NAME
              value: "{{ .Values.outputLogsLogGroupName }}"
              ### For calling the API GW
            - name: AGENT_API_GATEWAY_URL
              value: "{{ .Values.apiGatewayUrl }}"
            {{- include "env0-agent.customCertificatesNodeOptions" . | nindent 12 }}
            {{ if .Values.agentProxy.enableVcsWebhooksProxy }}
            - name: ENABLE_VCS_WEBHOOKS_PROXY
              value: "true"
            {{ end }}
            ### K8S Metadata
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{ if .Values.logger }}
            - name: CONSOLE_LOGS_FORMAT
              value: {{ .Values.logger.format }}
            - name: CONSOLE_LOGS_LEVEL
              value: {{ .Values.logger.level }}
            {{ end }}
      {{- include "env0-agent.tolerations" .Values.tolerations | nindent 6 -}}
      {{- include "env0-agent.affinity" .Values.affinity | nindent 6 -}}
{{- end }}
{{- end }}
