apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-trigger-service-account
  {{- with .Values.agentTrigger.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
