apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: env0
        operator: In
        {{ if ((.Values.agentProxy).enableVcsWebhooksProxy) }} # don't block agent-proxy if the webhooks proxy is enabled
        values: [ 'agent-trigger',  'agent-deployment' ]
        {{ else }}
        values: [ 'agent-trigger',  'agent-deployment', 'agent-proxy' ]
        {{ end }}
  policyTypes:
    - Ingress
