{{ if .Values.agentProxy }}
{{ if .Values.agentProxy.install }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.agentKey }}.agent-proxy-deployment
  labels:
    env0: agent-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      env0: agent-proxy
  template:
    metadata:
      labels:
        env0: agent-proxy
      annotations:
        forcePodRestart: {{ randAlphaNum 5 | quote }}
    spec:
      {{ if .Values.customCertificates }}
      volumes:
        - name: etc-ssl-certs
          emptyDir: { }
        - name: custom-certificates
          projected:
            sources:
            {{- range .Values.customCertificates }}
            - secret:
                name: {{ . }}
            {{- end }}
      {{ end }}
      restartPolicy: Always
      {{ if hasKey .Values "agentImagePullSecret" }}
      imagePullSecrets:
        - name: env0-image-pull-secret-{{ .Values.agentKey }}
      {{ end }}
      containers:
        - name: env0-agent-proxy
{{ include "env0-agent.strict-security-context" . | indent 10 }}
          image: {{ .Values.dockerImage }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            # update-ca-certificates must be called before node starts
            - update-ca-certificates; 
              node --enable-source-maps run-proxy.js;
          resources:
            limits:
              {{ if .Values.agentProxy.limits }}
              cpu: {{ .Values.agentProxy.limits.cpu }}
              memory: {{ .Values.agentProxy.limits.memory }}
              {{ else }}
              # backwards defaults
              cpu: 250m
              memory: 500Mi
              {{ end }}
            {{ if .Values.agentProxy.requests }}
            requests:
              cpu: "{{ .Values.agentProxy.requests.cpu }}"
              memory: "{{ .Values.agentProxy.requests.memory }}"
            {{ end }}
          {{ if .Values.customCertificates }}
          volumeMounts:
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: custom-certificates
              mountPath: /usr/local/share/ca-certificates
              readOnly: true          
          {{ end }}
          ports:
            - containerPort: 8000
          env:
{{ include "env0-agent.http-proxy" . | indent 12 }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: env0-secrets-{{ .Values.agentKey }}
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: env0-secrets-{{ .Values.agentKey }}
                  key: AWS_SECRET_ACCESS_KEY
            - name: BITBUCKET_SERVER_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: env0-secrets-{{ .Values.agentKey }}
                  key: BITBUCKET_SERVER_CREDENTIALS
            - name: GITLAB_ENTERPRISE_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: env0-secrets-{{ .Values.agentKey }}
                  key: GITLAB_ENTERPRISE_CREDENTIALS
            - name: GITLAB_ENTERPRISE_BASE_URL_SUFFIX
              value: {{ .Values.gitlabEnterpriseBaseUrlSuffix | default "" | quote  }}
            - name: GITHUB_ENTERPRISE_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env0-secrets-{{ .Values.agentKey }}
                  key: GITHUB_ENTERPRISE_APP_CLIENT_SECRET
            - name: GITHUB_ENTERPRISE_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: env0-secrets-{{ .Values.agentKey }}
                  key: GITHUB_ENTERPRISE_APP_PRIVATE_KEY
            - name: GITHUB_ENTERPRISE_APP_ID
              value: {{ .Values.githubEnterpriseAppId | default "" | quote }}
            - name: GITHUB_ENTERPRISE_APP_CLIENT_ID
              value: {{ .Values.githubEnterpriseAppClientId | default "" | quote }}
            - name: GITHUB_ENTERPRISE_APP_INSTALLATION_ID
              value: {{ .Values.githubEnterpriseAppInstallationId | default "" | quote }}
            - name: STAGE
              value: "{{ .Values.agentKey }}"
            - name: ENV0_STAGE
              value: "{{ .Values.stage }}"
            - name: IS_SELF_HOSTED_K8S
              value: "{{ .Values.isSelfHosted }}"
            - name: OUTPUT_LOGS_LOG_GROUP_NAME
              value: "{{ .Values.outputLogsLogGroupName }}"

              ### For calling the API GW
            - name: AGENT_API_GATEWAY_URL
              value: "{{ .Values.apiGatewayUrl }}"
            - name: DEPLOYMENT_TRIGGER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env0-secrets-{{ .Values.agentKey }}
                  key: DEPLOYMENT_TRIGGER_API_KEY

            {{ if .Values.customCertificates }}
            - name: NODE_EXTRA_CA_CERTS
              value: /etc/ssl/certs/ca-certificates.crt
            {{ end }}
            {{ if .Values.agentProxy.enableVcsWebhooksProxy }}
            - name: ENABLE_VCS_WEBHOOKS_PROXY
              value: "true"
            {{ end }}
            ### K8S Metadata
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{ if .Values.logger }}
            - name: CONSOLE_LOGS_FORMAT
              value: {{ .Values.logger.format }}
            - name: CONSOLE_LOGS_LEVEL
              value: {{ .Values.logger.level }}
            {{ end }}
      {{ if .Values.tolerations }}
      # Warning - every whitespace here matters
      tolerations: {{ range $i, $toleration := .Values.tolerations }}
        -
        {{ range $k, $v := $toleration }}  {{ $k }}: {{ $v }}
        {{ end }}{{ end }}
      {{ end }}
      {{ if .Values.affinity }}
      affinity: {{ .Values.affinity | toYaml | trim | nindent 8 }}
      {{ end }}
{{ end }}
{{ end }}
