apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.agentKey }}.agent-trigger-deployment
  labels:
    env0: agent-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      env0: agent-trigger
  template:
    metadata:
      labels:
        env0: agent-trigger
        {{- if .Values.agentAdditionalLabels }}
          {{- .Values.agentAdditionalLabels | toYaml | nindent 8 -}}
        {{- end }}
      annotations:
        forcePodRestart: {{ randAlphaNum 5 | quote }}
        {{- if .Values.agentAdditionalAnnotations }}
          {{- .Values.agentAdditionalAnnotations | toYaml | nindent 8 -}}
        {{- end }}
    spec:
      serviceAccountName: agent-trigger-service-account
      restartPolicy: Always
      volumes:
        - name: tmp
          emptyDir: { }
        {{- include "env0-agent.customCertificatesVolumes" . | nindent 8 }}
      {{- if or (hasKey .Values "agentImagePullSecret") (hasKey .Values "agentImagePullSecretRef") }}
      imagePullSecrets:
        - name: {{ if hasKey .Values "agentImagePullSecret" }}env0-image-pull-secret-{{ .Values.agentKey }}{{ else }}{{ .Values.agentImagePullSecretRef }}{{ end }}
      {{- end }}
      {{- if .Values.additionalAgentConfig }}
      {{- toYaml .Values.additionalAgentConfig | nindent 6 }}
      {{- end }}
      containers:
        - name: env0-agent-trigger
  {{ include "env0-agent.strict-security-context" . | indent 10 }}
          image: {{ .Values.dockerImage }}
          imagePullPolicy: Always
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- include "env0-agent.customCertificatesVolumesMounts" . | nindent 12 }}
          command: [ "/bin/sh", "-c" ]
          args:
            # update-ca-certificates must be called before node starts
            - update-ca-certificates;
              node --enable-source-maps run-agent-trigger.js;
          livenessProbe:
            exec:
              command:
                - rm
                - &livenessProbeFile /tmp/healthy
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
          resources:
            limits:
              cpu: {{ .Values.agentTrigger.limits.cpu | default "500m" }}
              memory: {{ .Values.agentTrigger.limits.memory | default "1000Mi" }}
            requests:
              cpu: {{ .Values.agentTrigger.requests.cpu | default "500m" }}
              memory: {{ .Values.agentTrigger.requests.memory | default "1000Mi" }}
          envFrom:
            - secretRef:
                name: env0-secrets-{{ .Values.agentKey }}
          {{- if .Values.env0ConfigSecretName }}
            - secretRef:
                name: {{ .Values.env0ConfigSecretName }}
          {{- end }}
          env:
{{ include "env0-agent.http-proxy" . | indent 12 }}
            - name: K8S_VERSION
              value: {{ .Capabilities.KubeVersion.Version }}
            - name: OUTPUT_LOGS_LOG_GROUP_NAME
              value: "{{ .Values.outputLogsLogGroupName }}"
            - name: STAGE
              value: "{{ .Values.agentKey }}"
            - name: ENV0_STAGE
              value: "{{ .Values.stage }}"
            - name: IS_SELF_HOSTED_K8S
              value: "{{ .Values.isSelfHosted }}"
            - name: K8S_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: CRON_JOB_NAME
              value: "{{ .Values.agentKey }}.deployment"
            - name: AGENT_TRIGGER_LIVENESS_PROBE_FILE
              value: *livenessProbeFile
            - name: FAILED_JOBS_HISTORY_LIMIT
              value: "{{ .Values.jobHistoryLimitFailure }}"
            - name: SUCCESSFUL_JOBS_HISTORY_LIMIT
              value: "{{ .Values.jobHistoryLimitSuccess }}"
            - name: DEPLOYMENT_POD_WARM_POOL_SIZE
              value: "{{ .Values.deploymentPodWarmPoolSize | default 0 }}"
            {{- if (.Values.agentThrottling | default (dict "enabled" true)).enabled  }}
            - name: AGENT_THROTTLING_ENABLED
              value: "true"
            - name: TASKS_POLLING_INTERVAL
              value: "{{ (.Values.agentThrottling | default dict).tasksPollingInterval | default 1000 }}"
            - name: MAX_CONCURRENT_JOBS_PER_ORGANIZATION
              value: "{{ (.Values.agentThrottling | default dict).maxConcurrentJobsPerOrganization | default 0 }}"
            {{- end }}
            {{- if .Values.driftDetection }}
            {{- if .Values.driftDetection.jobOverrides }}
            - name: DRIFT_DETECTION_JOB_OVERRIDES
              value: {{ .Values.driftDetection.jobOverrides | quote }}
            {{- end }}
            {{- end }}
            ### For calling the API GW
            - name: AGENT_API_GATEWAY_URL
              value: "{{ .Values.apiGatewayUrl }}"
            ### K8S Metadata
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{ if .Values.logger }}
            - name: CONSOLE_LOGS_FORMAT
              value: {{ .Values.logger.format }}
            - name: CONSOLE_LOGS_LEVEL
              value: {{ .Values.logger.level }}
            {{ end }}
            {{ if .Values.agentTrigger.maxOldSpaceSize }}
            - name: NODE_OPTIONS
              value: "--max-old-space-size={{ .Values.agentTrigger.maxOldSpaceSize }}"
            {{ end }}
            {{- include "env0-agent.agent-additional-env-vars" . | nindent 12 }}
            {{- include "env0-agent.customCertificatesNodeOptions" . | nindent 12 }}
      {{- include "env0-agent.tolerations" .Values.tolerations | nindent 6 }}
      {{- include "env0-agent.affinity" .Values.affinity | nindent 6 }}
