kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-trigger-role-{{ .Values.agentKey }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "list", "delete"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
