apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-deployment-role-binding-{{ .Values.agentKey }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.deploymentJobServiceAccountName | default "default" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: agent-deployment-role-{{ .Values.agentKey }}
  apiGroup: rbac.authorization.k8s.io
