{{ if (.Values.agentThrottling | default (dict "enabled" false)).enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacity-reservation
spec:
  replicas: {{ .Values.deploymentPodWarmPoolSize | default 0 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: capacity-placeholder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: capacity-placeholder
      annotations:
        kubernetes.io/description: "Capacity reservation"
    spec:
      priorityClassName: {{ .Values.agentKey }}-placeholder
      restartPolicy: Always
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10
          resources:
            limits:
            {{ if .Values.limits.cpu }}
              cpu: "{{ .Values.limits.cpu }}"
            {{ end }}
              memory: "{{ .Values.limits.memory }}"
            {{ if .Values.requests }}
            requests:
              cpu: "{{ .Values.requests.cpu }}"
              memory: "{{ .Values.requests.memory }}"
            {{ end }}
      {{- include "env0-agent.tolerations" (ternary .Values.tolerations .Values.deploymentTolerations (empty .Values.deploymentTolerations)) | nindent 6 -}}
      {{- include "env0-agent.affinity" (ternary .Values.affinity .Values.deploymentAffinity (empty .Values.deploymentAffinity)) | nindent 6 -}}
{{ end}}
