{{ if hasKey .Values "agentImagePullSecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: env0-image-pull-secret-{{ .Values.agentKey }}
data:
  .dockerconfigjson: {{ .Values.agentImagePullSecret }}
type: kubernetes.io/dockerconfigjson
{{ end }}
