apiVersion: v1
kind: Secret
metadata:
  name: env0-secrets-{{ .Values.agentKey }}
data:
{{- with .Values }}
  AWS_ACCESS_KEY_ID: {{ .awsAccessKeyIdEncoded | default "" | quote  }}
  AWS_SECRET_ACCESS_KEY: {{ .awsSecretAccessKeyEncoded | default "" | quote  }}
  DEPLOYMENT_TRIGGER_API_KEY : {{ .env0ApiGwKeyEncoded | default "" | quote  }}
  ASSUMER_ACCESS_KEY_ID: {{ .assumerKeyIdEncoded | default "" | quote }}
  ASSUMER_SECRET_ACCESS_KEY: {{ .assumerSecretEncoded | default "" | quote }}
  INFRACOST_API_KEY: {{ .infracostApiKeyEncoded | default "" | quote }}
  CUSTOMER_AWS_ACCESS_KEY_ID: {{ .customerAwsAccessKeyIdEncoded | default "" | quote }}
  CUSTOMER_AWS_SECRET_ACCESS_KEY: {{ .customerAwsSecretAccessKeyEncoded | default "" | quote }}
  CUSTOMER_GOOGLE_PROJECT: {{ .customerGoogleProject | default "" | quote }}
  CUSTOMER_GOOGLE_CREDENTIALS: {{ .customerGoogleCredentials | default "" | quote }}
  CUSTOMER_AZURE_CLIENT_ID: {{ .customerAzureClientId | default "" | quote }}
  CUSTOMER_AZURE_CLIENT_SECRET: {{ .customerAzureClientSecret | default "" | quote }}
  CUSTOMER_AZURE_TENANT_ID: {{ .customerAzureTenantId | default "" | quote }}
  BITBUCKET_SERVER_CREDENTIALS: {{ .bitbucketServerCredentialsEncoded | default "" | quote }}
  GITLAB_ENTERPRISE_CREDENTIALS: {{ .gitlabEnterpriseCredentialsEncoded | default "" | quote }}
  GITHUB_ENTERPRISE_APP_CLIENT_SECRET: {{ .githubEnterpriseAppClientSecretEncoded | default "" | quote }}
  GITHUB_ENTERPRISE_APP_PRIVATE_KEY: {{ .githubEnterpriseAppPrivateKeyEncoded | default "" | quote }}
  ENV0_ENVIRONMENT_OUTPUT_ENCRYPTION_KEY: {{ .environmentOutputEncryptionKey | default "" | quote }}

  {{ if .customerOracleCredentials }}
  CUSTOMER_ORACLE_TENANCY_OCID: {{ .customerOracleCredentials.tenancyOCIDEncoded | default "" | quote }}
  CUSTOMER_ORACLE_USER_OCID: {{ .customerOracleCredentials.userOCIDEncoded | default "" | quote }}
  CUSTOMER_ORACLE_API_KEY_FINGERPRINT: {{ .customerOracleCredentials.apiKeyFingerprintEncoded | default "" | quote }}
  CUSTOMER_ORACLE_API_KEY_PRIVATE_KEY: {{ .customerOracleCredentials.apiKeyPrivateKeyEncoded | default "" | quote }}
  ORACLE_SECRETS_REGION: {{ .customerOracleCredentials.secretsRegion | default "" | quote }}
  {{ end }}

  {{ if and .vault .vault.encodedPassword }}
  CUSTOMER_VAULT_PASSWORD: {{ .vault.encodedPassword | default "" | quote }}
  {{ end }}
  # customerVaultTokenEncoded and customerVaultUrl are deprecated
  {{ if and .vault .vault.encodedToken }}
  CUSTOMER_VAULT_TOKEN: {{ .vault.encodedToken | default "" | quote }}
  {{ end }}
  {{ if .customerVaultTokenEncoded }}
  CUSTOMER_VAULT_TOKEN: {{ .customerVaultTokenEncoded | default "" | quote }}
  {{ end }}
  {{ if .alternativeLogLocation }}
  ALT_LOGS_DYNAMO_WRITER_EXTERNAL_ID : {{ .alternativeLogLocation.dynamoWriterExternalIdEncoded | default "" | quote }}
  {{ end }}
  {{ if .env0StateEncryptionKey }}
  ENV0_STATE_ENCRYPTION_KEY: {{ .env0StateEncryptionKey | default "" | quote }}
  {{ end }}
{{- end }}
